<a href="https://colab.research.google.com/github/asthaofficals/Datascience/blob/main/Python_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***What are NumPy Arrays?***

NumPy is a Python package that stands for ‘Numerical Python’. It is the core library for scientific computing, which contains a powerful n-dimensional array object.


*   NumPy uses much less memory to store data.
*   NumPy arrays are faster and more compact than Python lists.

***Where is NumPy used?***

Python NumPy arrays provide tools for integrating C, C++, etc. It is also useful in linear algebra, random number capability etc. NumPy array can also be used as an efficient multi-dimensional container for generic data. 

***Python NumPy Array:***
Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements.







In [ ]:
#installing numpy
!pip install numpy

***Python NumPy Array v/s List***
***Why NumPy is used in Python? ***

We use python NumPy array instead of a list because of the below three reasons:

1. Less Memory

2. Fast

3. Convenient

The very first reason to choose python NumPy array is that it occupies less memory as compared to list. Then, it is pretty fast in terms of execution and at the same time, it is very convenient to work with NumPy.So these are the major advantages that Python NumPy array has over list. 


***Python NumPy Operations***

You can find the dimension of the array, whether it is a two-dimensional array or a single dimensional array. So, let us see this practically how we can find the dimensions. In the below code, with the help of ‘ndim’ function, I can find whether the array is of single dimension or multi dimension.

In [ ]:
import numpy as np
a = np.array([(5,4,6),(1,5,8)])
print(a.ndim)

2


***itemsize:***

You can calculate the byte size of each element. In the below code, I have defined a single dimensional array and with the help of ‘itemsize’ function, we can find the size of each element.

In [ ]:
import numpy as np
a = np.array([(3,4,5)])
print(a.itemsize)

8


***dtype:***

You can find the data type of the elements that are stored in an array. So, if you want to know the data type of a particular element, you can use ‘dtype’ function which will print the datatype along with the size. In the below code, I have defined an array where I have used the same function.

In [ ]:
import numpy as np
a = np.array([(2,3,4)])
print(a.dtype)

int64


As you can see, the data type of the array is integer 64 bits. Similarly, you can find the size and shape of the array using ‘size’ and ‘shape’ function respectively.

In [ ]:
import numpy as np
a = np.array([(2,3,4,5,6,7)])
print(a.size)
print(a.shape)

6
(1, 6)


***Reshape:***

Reshape is when you change the number of rows and columns which gives a new view to an object. Now, let us take an example to reshape the below array:

In [ ]:
import numpy as np
a = np.array([(11,12,10),(15,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[11 12 10]
 [15 12 13]]
[[11 12]
 [10 15]
 [12 13]]


***slicing:***

As you can see the ‘reshape’ function has showed its magic. Now, let’s take another operation i.e Slicing. Slicing is basically extracting particular set of elements from an array. This slicing operation is pretty much similar to the one which is there in the list as well. Consider the following example:

In [ ]:
import numpy as np
a=np.array([(2,3,4,5),(2,4,8,6)])
print(a[1,2])

8


Taking one step forward, let’s say we need the 2nd element from the zeroth and first index of the array. ***Let’s see how you can perform this operation:***

In [ ]:
import numpy as np
a=np.array([(1,2,3,4),(3,4,5,6)])
print(a[0:,2])

[3 5]


***linspace ***

This is another operation in python numpy which returns evenly spaced numbers over a specified interval. ***Consider the below example:***

In [ ]:
import numpy as np
a=np.linspace(1,3,10)
print(a)

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


***max/ min***

Next, we have some more operations in numpy such as to find the minimum, maximum as well the sum of the numpy array. Let’s go ahead in python numpy tutorial and execute it practically.

In [ ]:
import numpy as np
 
a= np.array([1,2,3])
print(a.min())
print(a.max())
print(a.sum())

1
3
6


***Square Root & Standard Deviation***

There are various mathematical functions that can be performed using python numpy. You can find the square root, standard deviation of the array. 

In [ ]:
import numpy as np
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))
print(np.std(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


***Addition Operation***

You can perform more operations on numpy array i.e addition, subtraction,multiplication and division of the two matrices. 

In [ ]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x+y)

[[ 2  4  6]
 [ 6  8 10]]


In [ ]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)
print(x*y)
print(x/y)

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


***Vertical & Horizontal Stacking***

If you want to concatenate two arrays and not just add them, you can perform it using two ways – vertical stacking and horizontal stacking. 

In [ ]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(np.vstack((x,y)))
print(np.hstack((x,y)))

[[1 2 3]
 [3 4 5]
 [1 2 3]
 [3 4 5]]
[[1 2 3 1 2 3]
 [3 4 5 3 4 5]]


***ravel***

There is one more operation where you can convert one numpy array into a single column i.e ravel.

In [ ]:
import numpy as np
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())

[1 2 3 3 4 5]
